# Generated by Django 3.2.9 on 2021-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='peliculas',
        ),
    ]
