# Generated by Django 3.2.9 on 2021-12-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_auto_20211207_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='tittle',
            new_name='title',
        ),
    ]
